# Google Cloud Build configuration for Next.js application
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/photo-info-extractor:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/photo-info-extractor:latest',
      '.'
    ]

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/photo-info-extractor:$COMMIT_SHA'
    ]

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/photo-info-extractor:latest'
    ]

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'photo-info-extractor',
      '--image', 'gcr.io/$PROJECT_ID/photo-info-extractor:$COMMIT_SHA',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production',
      '--timeout', '300'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/photo-info-extractor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/photo-info-extractor:latest'

# Build configuration
options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Increase disk size for large builds
  diskSizeGb: 100
  
  # Enable logging
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build process (20 minutes)
timeout: '1200s'

# Substitutions for environment variables
substitutions:
  _REGION: 'asia-northeast1'
  _SERVICE_NAME: 'photo-info-extractor'

# Tags for organizing builds
tags:
  - 'photo-info-extractor'
  - 'nextjs'
  - 'production'
